<?php

/**
 * The public-facing functionality of WP Pop!
 *
 * @since   0.1.0
 * @package Wp_Pop
 */

if ( ! defined( 'WPINC' ) ) {
	die;
}

class Wp_Pop_Public {

	protected $plugin_name;

	protected $version;

	/** @var WP_Post[]|null Cached active popups for the current request. */
	private $active_popups_cache = null;

	public function __construct( $plugin_name, $version ) {
		$this->plugin_name = $plugin_name;
		$this->version     = $version;

		// Register core WordPress content processing on a dedicated filter.
		// Popup content is run through wp_pop_popup_content instead of the_content
		// so that theme/plugin ad injectors hooked onto the_content are never invoked.
		add_filter( 'wp_pop_popup_content', 'do_blocks',              9  );
		add_filter( 'wp_pop_popup_content', 'wptexturize'                );
		add_filter( 'wp_pop_popup_content', 'convert_smilies',        20 );
		add_filter( 'wp_pop_popup_content', 'wpautop'                    );
		add_filter( 'wp_pop_popup_content', 'shortcode_unautop'          );
		add_filter( 'wp_pop_popup_content', 'wp_filter_content_tags', 12 );
		add_filter( 'wp_pop_popup_content', 'do_shortcode',           11 );
	}

	public function enqueue_styles() {
		wp_enqueue_style(
$this->plugin_name,
			WP_POP_PLUGIN_URL . 'public/css/wp-pop-public.css',
			array(),
			$this->version,
			'all'
		);
	}

	public function enqueue_scripts() {
		// Only enqueue the view module when there are active popups on this page.
		$active = $this->resolve_active_popups();

		if ( empty( $active ) ) {
			return;
		}

		// Load asset manifest generated by webpack (includes version hash + deps).
		$asset_file = WP_POP_PLUGIN_DIR . 'build/view.asset.php';
		$asset      = file_exists( $asset_file ) ? require $asset_file : array(
			'dependencies' => array( '@wordpress/interactivity' ),
			'version'      => $this->version,
		);

		// Register & enqueue as a Script Module (outputs <script type="module">).
		wp_register_script_module(
			'@wp-pop/view',
			WP_POP_PLUGIN_URL . 'build/view.js',
			array_map(
				function ( $dep ) {
					return array( 'id' => $dep, 'import' => 'static' );
				},
				$asset['dependencies']
			),
			$asset['version']
		);
		wp_enqueue_script_module( '@wp-pop/view' );

		// Expose JS config to the frontend store via an inline script.
		// wp_add_inline_script() only works with classic wp_scripts() handles,
		// not with script-module handles, so we output a plain <script> tag
		// in the footer with priority 1 (before our module runs).
		$config_js = 'window.wpPop = ' . wp_json_encode( array(
			'ajaxUrl'        => admin_url( 'admin-ajax.php' ),
			'nonce'          => wp_create_nonce( 'wp_pop_track' ),
		) ) . ';';
		add_action( 'wp_footer', static function() use ( $config_js ) {
			echo '<script id="wp-pop-config">' . $config_js . "</script>\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		}, 1 );
	}

	/**
	 * Renders a popup via the [wp_pop id="123"] shortcode.
	 *
	 * @param  array $atts Shortcode attributes: id (required).
	 * @return string HTML output.
	 */
	public function render_shortcode( $atts ) {
		$atts = shortcode_atts( array( 'id' => 0 ), $atts, 'wp_pop' );
		$popup_id = absint( $atts['id'] );
		if ( ! $popup_id ) {
			return '';
		}
		$popup = get_post( $popup_id );
		if ( ! $popup || 'wp_pop' !== $popup->post_type ) {
			return '';
		}

		ob_start();
		$this->render_popup( $popup );
		return ob_get_clean();
	}

	/**
	 * Outputs all active popups for the current page in wp_footer.
	 * A/B test pairs are injected: for any popup that is Variant A of an active
	 * test, Variant B is also rendered (both carry A/B context so the frontend
	 * can pick one and keep the other dormant).
	 */
	public function render_popups() {
		$popups = $this->resolve_active_popups();

		// Expand list with A/B test variants.
		$ab_testing = new Wp_Pop_Ab_Testing();
		$entries    = $ab_testing->expand_with_test_variants( $popups );

		foreach ( $entries as $entry ) {
			$this->render_popup( $entry['popup'], $entry['ab_context'] );
		}
	}

	/**
	 * Returns active popups for the current page, cached per request.
	 * Uses the full targeting engine (geo, role, device) when available,
	 * otherwise falls back to the basic scope/schedule check.
	 *
	 * @return WP_Post[]
	 */
	private function resolve_active_popups() {
		if ( null !== $this->active_popups_cache ) {
			return $this->active_popups_cache;
		}

		if ( class_exists( 'Wp_Pop_Targeting' ) ) {
			$targeting                 = new Wp_Pop_Targeting();
			$this->active_popups_cache = $targeting->get_active_popups_for_current_page();
		} else {
			$this->active_popups_cache = $this->get_active_popups_for_current_page();
		}

		return $this->active_popups_cache;
	}

	/**
	 * Returns published wp_pop posts that should appear on the current page.
	 *
	 * @return WP_Post[]
	 */
	protected function get_active_popups_for_current_page() {
		static $active_popups = null;

		if ( null !== $active_popups ) {
			return $active_popups;
		}

		$all_popups = get_posts(
array(
'post_type'      => 'wp_pop',
				'post_status'    => 'publish',
				'posts_per_page' => -1,
				'no_found_rows'  => true,
			)
		);

		$current_page_id = get_queried_object_id();
		$active_popups   = array();

		foreach ( $all_popups as $popup ) {
			$scope = get_post_meta( $popup->ID, '_wp_pop_display_scope', true );

			if ( 'specific' === $scope ) {
				$specific_pages = get_post_meta( $popup->ID, '_wp_pop_specific_pages', true );
				if ( ! is_array( $specific_pages ) || ! in_array( $current_page_id, $specific_pages, false ) ) { // phpcs:ignore WordPress.PHP.StrictInArray.MissingTrueStrict
					continue;
				}
			}

			// Schedule check: skip if we're outside the configured date/time window.
			$start_date = get_post_meta( $popup->ID, '_wp_pop_start_date', true );
			$start_time = get_post_meta( $popup->ID, '_wp_pop_start_time', true );
			$end_date   = get_post_meta( $popup->ID, '_wp_pop_end_date', true );
			$end_time   = get_post_meta( $popup->ID, '_wp_pop_end_time', true );

			if ( $start_date ) {
				$fmt     = $start_time ? 'Y-m-d H:i' : 'Y-m-d';
				$now     = current_time( $fmt );
				$compare = $start_time ? $start_date . ' ' . $start_time : $start_date;
				if ( $now < $compare ) {
					continue;
				}
			}

			if ( $end_date ) {
				$fmt     = $end_time ? 'Y-m-d H:i' : 'Y-m-d';
				$now     = current_time( $fmt );
				$compare = $end_time ? $end_date . ' ' . $end_time : $end_date;
				if ( $now > $compare ) {
					continue;
				}
			}

			$active_popups[] = $popup;
		}

		return $active_popups;
	}

	/**
	 * Renders a single popup's HTML with data-wp-* Interactivity API attributes.
	 *
	 * Themes can override the template by placing a file under their theme folder:
	 *   wp-pop/popup-{id}.php  — for a specific popup
	 *   wp-pop/popup.php       — for all popups (fallback)
	 *
	 * @param WP_Post $popup
	 * @param array   $ab_context  Optional A/B context keys: abTestId, abVariant, abWeightA.
	 */
	protected function render_popup( $popup, array $ab_context = array() ) {
		$id = $popup->ID;

		// ---- Helper: meta with option fallback --------------------------------
		$meta = function( $key, $option_key = '', $default = '' ) use ( $id ) {
			$val = get_post_meta( $id, $key, true );
			if ( '' === $val || false === $val ) {
				$val = $option_key ? get_option( $option_key, $default ) : $default;
			}
			return $val;
		};

		// ---- Trigger / Frequency --------------------------------------------
		$trigger           = $meta( '_wp_pop_trigger', 'wp_pop_default_trigger', 'time' );
		$trigger_delay     = (int) $meta( '_wp_pop_trigger_delay', 'wp_pop_default_delay', 0 );
		$scroll_threshold  = (int) $meta( '_wp_pop_scroll_threshold', 'wp_pop_default_scroll_threshold', 50 );
		$click_selector    = $meta( '_wp_pop_click_selector', '', '' );
		$inactivity_sec    = (int) $meta( '_wp_pop_inactivity_seconds', '', 30 );
		$element_selector  = $meta( '_wp_pop_element_selector', '', '' );
		$wc_trigger        = $meta( '_wp_pop_wc_trigger', '', '' );
		$frequency         = $meta( '_wp_pop_frequency', 'wp_pop_default_frequency', 'session' );
		$retrigger_minutes = (int) $meta( '_wp_pop_retrigger_minutes', '', 60 );

		// ---- Appearance -----------------------------------------------------
		$popup_type        = $meta( '_wp_pop_popup_type', 'wp_pop_default_popup_type', 'modal' );
		$animation         = $meta( '_wp_pop_animation', 'wp_pop_default_animation', 'fade' );
		$width             = $meta( '_wp_pop_width', '', '600px' );
		$overlay           = (bool) $meta( '_wp_pop_overlay', '', true );
		$overlay_color     = $meta( '_wp_pop_overlay_color', 'wp_pop_default_overlay_color', '#000000' );
		$overlay_opacity   = (float) $meta( '_wp_pop_overlay_opacity', 'wp_pop_default_overlay_opacity', 0.65 );
		$border_radius     = (int) $meta( '_wp_pop_border_radius', 'wp_pop_default_border_radius', 8 );
		$padding           = $meta( '_wp_pop_padding', 'wp_pop_default_padding', '20px' );
		$close_color       = $meta( '_wp_pop_close_color', 'wp_pop_default_close_color', '#333333' );
		$close_delay       = (int) $meta( '_wp_pop_close_delay', '', 0 );
		$close_on_outside  = (bool) $meta( '_wp_pop_close_on_outside_click', '', true );
		$close_on_esc      = (bool) $meta( '_wp_pop_close_on_esc', '', true );
		$show_close_button = (bool) $meta( '_wp_pop_show_close_button', '', true );

		// ---- A/B Testing (popup-pair based) --------------------------------
		// Old single-popup CSS-class variant fields are intentionally omitted.
		// A/B context is injected by Wp_Pop_Ab_Testing::expand_with_test_variants().

		// ---- Conversion Tracking -------------------------------------------
		$success_url = $meta( '_wp_pop_success_url', '', '' );

		// ---- CSS custom properties ------------------------------------------
		$css_vars = sprintf(
			'--wp-pop-overlay-bg:%s;--wp-pop-border-radius:%dpx;--wp-pop-dialog-padding:%s;--wp-pop-close-color:%s;--wp-pop-max-width:%s',
			$this->hex_opacity_to_rgba( $overlay_color, $overlay_opacity ),
			$border_radius,
			esc_attr( $padding ),
			esc_attr( $close_color ),
			esc_attr( $width )
		);

		// ---- Build context JSON for Interactivity API -----------------------
		$context = array(
			'popupId'            => $id,
			'trigger'            => $trigger,
			'triggerDelay'       => $trigger_delay,
			'scrollThreshold'    => $scroll_threshold,
			'clickSelector'      => $click_selector,
			'inactivitySeconds'  => $inactivity_sec,
			'elementSelector'    => $element_selector,
			'wcTrigger'          => $wc_trigger,
			'frequency'          => $frequency,
			'retriggerMinutes'   => $retrigger_minutes,
			'popupType'          => $popup_type,
			'animation'          => $animation,
			'overlay'            => $overlay,
			'closeOnOutsideClick'=> $close_on_outside,
			'closeOnEsc'         => $close_on_esc,
			'showCloseButton'    => $show_close_button,
			'closeDelay'         => $close_delay,
			// A/B test context — empty for popups not in a test.
			'abTestId'           => $ab_context['abTestId']  ?? null,
			'abVariant'          => $ab_context['abVariant'] ?? null,
			'abWeightA'          => $ab_context['abWeightA'] ?? null,
			'successUrl'         => $success_url,
			'activeVariant'      => '',
			'testMode'           => (bool) $meta( '_wp_pop_test_mode', '', false ) && current_user_can( 'manage_options' ),
		);

		$popup_element_id = 'wp-pop-' . $id;
		$content          = apply_filters( 'wp_pop_popup_content', $popup->post_content );
		$template         = $this->locate_popup_template( $id );

		include $template; // phpcs:ignore WPThemeReview.CoreFunctionality.FileInclude.FileIncludeFound
	}

	/**
	 * Resolves the popup width preset to a CSS max-width value.
	 *
	 * @param  string $preset     Preset key: small|medium|large|full|custom.
	 * @param  mixed  $custom_rem Numeric rem value used when $preset is 'custom'.
	 * @return string CSS value suitable for max-width.
	 */
	protected function resolve_width( $preset, $custom_rem ) {
		$presets = array(
			'small'  => '26rem',
			'medium' => '40rem',
			'large'  => '56rem',
			'full'   => 'none',
		);
		if ( 'custom' === $preset ) {
			$n = max( 10.0, min( 200.0, (float) $custom_rem ) );
			return round( $n, 1 ) . 'rem';
		}
		return isset( $presets[ $preset ] ) ? $presets[ $preset ] : '40rem';
	}

	/**
	 * Converts a hex colour + opacity float into an rgba() string.
	 *
	 * @param string $hex     Hex colour, e.g. '#000000' or '#000'.
	 * @param float  $opacity Value between 0 and 1.
	 * @return string
	 */
	protected function hex_opacity_to_rgba( $hex, $opacity ) {
		$hex = ltrim( $hex, '#' );
		if ( 3 === strlen( $hex ) ) {
			$hex = $hex[0] . $hex[0] . $hex[1] . $hex[1] . $hex[2] . $hex[2];
		}
		$r = hexdec( substr( $hex, 0, 2 ) );
		$g = hexdec( substr( $hex, 2, 2 ) );
		$b = hexdec( substr( $hex, 4, 2 ) );
		return sprintf( 'rgba(%d,%d,%d,%.2f)', $r, $g, $b, max( 0.0, min( 1.0, $opacity ) ) );
	}

	/**
	 * Locates the best-matching popup template file.
	 *
	 * Checks the active theme (and child theme) first, then falls back to the
	 * plugin's own default template. Theme files must live inside a wp-pop/
	 * subdirectory within the theme folder.
	 *
	 * Priority:
	 *   1. {theme}/wp-pop/popup-{id}.php  — per-popup override
	 *   2. {theme}/wp-pop/popup.php        — site-wide theme override
	 *   3. Plugin default template
	 *
	 * @param  int    $popup_id Post ID of the popup.
	 * @return string Absolute path to the template file to load.
	 */
	protected function locate_popup_template( $popup_id ) {
		$theme_files = array(
			'wp-pop/popup-' . absint( $popup_id ) . '.php',
			'wp-pop/popup.php',
		);

		$located = locate_template( $theme_files, false, false );

		if ( $located ) {
			return $located;
		}

		return WP_POP_PLUGIN_DIR . 'public/partials/wp-pop-popup.php';
	}
}
